
services:
   hosped-front:
      restart: always
      environment:
        - TZ=America/Sao_Paulo
        - VITE_API_ENDPOINT=https://api.travacarrinho.com.br/api/
      build:
         context: .
         dockerfile: Dockerfile
      container_name: "frontend-hospede"
      ports:
       - 8000:80
       - 8001:443