
services:
   hosped-front:
      restart: always
      environment:
        - TZ=America/Sao_Paulo
        - VITE_API_ENDPOINT=http://localhost:5288/api/
        - VITE_REPORT_API_ENDPOINT=https://botreportapi.manja.tec.br/api/
      build:
         context: .
         dockerfile: Dockerfile
      container_name: "frontend-hospede"
      ports:
       - 3000:80
       - 3001:443